# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: "https://thomasmcleanjr.cv"
baseurl: "" # left blank right

# Website info
title: My Portfolio
description: My Professional Portfolio and Resume
cover: assets/images/downtown.png
logo: assets/images/owl.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
CNAME: thomasmcleanjr.cv #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
contact: True
# subscribers = Allows floating navbar to display contact-me button
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
linkedin: /in/tmclean93 # replace by your username
github: Thomasmclean993 # replace by your username
email: Thomas.McLean993+contact@gmail.com 

# Disqus
disqus: False
disqus_shortname: jekyllt # replace with your disqus username

# Google Analytics
google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /Portfolio-site/:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for building master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: thomasmclean993   
repo: Portfolio-site
branch: main
destination: _site
production_url: https://thomasmclean993.github.io/Portfolio-site/
source_url: https://github.com/thomasmclean993/Portfolio-site/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
